name: "Publish Docker Images"
on:
  push:
    branches:
      - main
  release:
    types:
      - released

env:
  DOCKER_ARCHS: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/arm/v5,linux/arm/v4,linux/ppc64le,linux/s390x,linux/s390,linux/mips64,linux/mips64le,linux/mips,linux/mipsle,linux/386,linux/ppc64,linux/ppc

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Publish Docker Image
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get Version and Set in Env
        shell: node {0}
        run: |
          const fs = require("fs");
          const { version } = require(process.cwd()+"/package.json");
          console.log(version);
          fs.appendFileSync(process.env.GITHUB_ENV, `CoreVersion=${version}`)

      - name: Build Bds Maneger Core (Release)
        uses: docker/build-push-action@v2
        if: github.event_name == 'release'
        with:
          push: true
          tags: |
            ghcr.io/sirherobrine23/javascript_releases_packages:latest
            ghcr.io/sirherobrine23/javascript_releases_packages:${{ env.CoreVersion }}
          platforms: ${{ env.DOCKER_ARCHS }}

      - name: Build Bds Maneger Core (Main)
        uses: docker/build-push-action@v2
        if: github.event_name != 'release'
        with:
          push: true
          tags: ghcr.io/sirherobrine23/javascript_releases_packages:nightly
          platforms: ${{ env.DOCKER_ARCHS }}